/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */
'use strict';var l=require("lexical"),t=require("@lexical/list"),z=require("@lexical/rich-text"),aa=require("@lexical/utils"),A=require("@lexical/code"),G=require("@lexical/link");function H(a,b){let c={};for(let d of a)a=b(d),c[a]?c[a].push(d):c[a]=[d];return c}function I(a){a=H(a,b=>b.type);return{element:a.element||[],textFormat:a["text-format"]||[],textMatch:a["text-match"]||[]}}let J=/[!-/:-@[-`{-~\s]/;
function ba(a){let b=I(a),c=b.textFormat.filter(d=>1===d.format.length);return d=>{let e=[];d=(d||l.$getRoot()).getChildren();for(let f of d)d=ca(f,b.element,c,b.textMatch),null!=d&&e.push(d);return e.join("\n\n")}}function ca(a,b,c,d){for(let e of b){let f=e.export(a,g=>K(g,b,c,d));if(null!=f)return f}return l.$isElementNode(a)?K(a,b,c,d):l.$isDecoratorNode(a)?a.getTextContent():null}
function K(a,b,c,d){let e=[];a=a.getChildren();a:for(let g of a){if(l.$isElementNode(g))for(let h of b){var f=h.export(g,k=>K(k,b,c,d));if(null!=f){e.push(f);a.indexOf(g)!==a.length-1&&e.push("\n");continue a}}for(let h of d)if(f=h.export(g,k=>K(k,b,c,d),(k,p)=>L(k,p,c)),null!=f){e.push(f);continue a}l.$isLineBreakNode(g)?e.push("\n"):l.$isTextNode(g)?e.push(L(g,g.getTextContent(),c)):l.$isElementNode(g)?(e.push(K(g,b,c,d)),a.indexOf(g)!==a.length-1&&e.push("\n","\n")):l.$isDecoratorNode(g)&&e.push(g.getTextContent())}return e.join("")}
function L(a,b,c){let d=b.trim(),e=d,f=new Set;for(let h of c){c=h.format[0];let k=h.tag;if(M(a,c)&&!f.has(c)){f.add(c);var g=N(a,!0);M(g,c)||(e=k+e);g=N(a,!1);M(g,c)||(e+=k)}}return b.replace(d,e)}
function N(a,b){let c=b?a.getPreviousSibling():a.getNextSibling();c||(a=a.getParentOrThrow(),a.isInline()&&(c=b?a.getPreviousSibling():a.getNextSibling()));for(;c;){if(l.$isElementNode(c)){if(!c.isInline())break;a=b?c.getLastDescendant():c.getFirstDescendant();if(l.$isTextNode(a))return a;c=b?c.getPreviousSibling():c.getNextSibling()}if(l.$isTextNode(c))return c;if(!l.$isElementNode(c))break}return null}function M(a,b){return l.$isTextNode(a)&&a.hasFormat(b)}
let O="undefined"!==typeof window&&"undefined"!==typeof window.document&&"undefined"!==typeof window.document.createElement,da=O&&"documentMode"in document?document.documentMode:null;O&&/Mac|iPod|iPhone|iPad/.test(navigator.platform);O&&/^(?!.*Seamonkey)(?=.*Firefox).*/i.test(navigator.userAgent);O&&"InputEvent"in window&&!da?"getTargetRanges"in new window.InputEvent("input"):!1;
let P=O&&/Version\/[\d.]+.*Safari/.test(navigator.userAgent),Q=O&&/iPad|iPhone|iPod/.test(navigator.userAgent)&&!window.MSStream,ea=O&&/^(?=.*Chrome).*/i.test(navigator.userAgent),R=O&&/AppleWebKit\/[\d.]+/.test(navigator.userAgent)&&!ea,fa=/^\s{0,3}$/;
function S(a,b,c){let d=b.length;var e=c.textFormat;var f={};var g={},h=[];for(var k of e){({tag:e}=k);f[e]=k;var p=e.replace(/(\*|\^|\+)/g,"\\$1");h.push(p);g[e]=P||Q||R?new RegExp(`(${p})(?![${p}\\s])(.*?[^${p}\\s])${p}(?!${p})`):new RegExp(`(?<![\\\\${p}])(${p})((\\\\${p})?.*?[^${p}\\s](\\\\${p})?)((?<!\\\\)|(?<=\\\\\\\\))(${p})(?![\\\\${p}])`)}f={fullMatchRegExpByTag:g,openTagsRegExp:new RegExp((P||Q||R?"":"(?<![\\\\])")+"("+h.join("|")+")","g"),transformersByTag:f};for(g=0;g<d;){h=b[g];p=!1;
for(let m of c.element)if(k=h.match(m.regExp),m.getNumberOfLines&&(e=m.getNumberOfLines(b,g),!(g+e>b.length)&&k)){p=l.$createParagraphNode();a.append(p);S(p,b.slice(g+1,g+e),c);m.replace(a.getLastChild(),a.getLastChild().getChildren(),k,!0);g+=e;g<d&&(m.closeRegExp&&b[g].match(m.closeRegExp)||b[g].match(m.regExp))&&g++;p=!0;break}if(p)continue;var B=h,u=a,q=c.element;k=f;e=c.textMatch;p=B.trimEnd();let r=l.$createTextNode(p);h=l.$createParagraphNode();h.append(r);u.append(h);for(let {regExp:m,replace:n}of q)if(u=
B.match(m)){B=B.slice(u[0].length);r.setTextContent(B);n(h,[r],u,!0);break}T(r,k,e);h.isAttached()&&0<p.length&&(k=h.getPreviousSibling(),l.$isParagraphNode(k)||z.$isQuoteNode(k)||t.$isListNode(k))&&(e=k,t.$isListNode(k)&&(k=k.getLastDescendant(),e=null==k?null:aa.$findMatchingParent(k,t.$isListItemNode)),null!=e&&0<e.getTextContentSize()&&(e.splice(e.getChildrenSize(),0,[l.$createLineBreakNode(),...h.getChildren()]),h.remove()));g++}}
function U(a){a=a.getChildren();for(let b of a){a:{a=b;if(!l.$isParagraphNode(a)){a=!1;break a}let c=a.getFirstChild();a=null==c||1===a.getChildrenSize()&&l.$isTextNode(c)&&fa.test(c.getTextContent())}a?b.remove():l.$isElementNode(b)&&U(b)}}function ha(a){let b=I(a);return(c,d)=>{c=c.split("\n");d=d||l.$getRoot();d.clear();S(d,c,b);U(d);null!==l.$getSelection()&&d.selectEnd()}}
function T(a,b,c){var d=a.getTextContent();let e=ia(d,b);if(e){var f,g;if(e[0]===d)var h=a;else{d=e.index||0;let k=d+e[0].length;0===d?[h,f]=a.splitText(k):[g,h,f]=a.splitText(d,k)}h.setTextContent(e[2]);if(a=b.transformersByTag[e[1]])for(let k of a.format)h.hasFormat(k)||h.toggleFormat(k);h.hasFormat("code")||T(h,b,c);g&&T(g,b,c);f&&T(f,b,c)}else V(a,c)}
function V(a,b){a:for(;a;){for(let c of b){let d=a.getTextContent().match(c.importRegExp);if(!d)continue;let e=d.index||0,f=e+d[0].length,g,h,k;0===e?[g,a]=a.splitText(f):[h,g,k]=a.splitText(e,f);h&&V(h,b);k&&(a=k);c.replace(g,d);continue a}break}}
function ia(a,b){var c=a.match(b.openTagsRegExp);if(null==c)return null;for(let f of c){var d=f.replace(/^\s/,"");c=b.fullMatchRegExpByTag[d];if(null!=c&&(c=a.match(c),d=b.transformersByTag[d],null!=c&&null!=d)){if(!1!==d.intraword)return c;var {index:e=0}=c;d=a[e-1];e=a[e+c[0].length];if(!(d&&!J.test(d)||e&&!J.test(e)))return c}}return null}function ja(a,b,c){let d=c.length;for(;b>=d;b--){let e=b-d;if(ka(a,e,c,0,d)&&" "!==a[e+d])return e}return-1}
function ka(a,b,c,d,e){for(let f=0;f<e;f++)if(a[b+f]!==c[d+f])return!1;return!0}
let W=a=>(b,c,d)=>{d=a(d);d.append(...c);b.replace(d)},X=a=>(b,c,d)=>{var e=b.getPreviousSibling(),f=b.getNextSibling();const g=t.$createListItemNode("check"===a?"x"===d[3]:void 0);t.$isListNode(f)&&f.getListType()===a?(e=f.getFirstChild(),null!==e?e.insertBefore(g):f.append(g),b.remove()):t.$isListNode(e)&&e.getListType()===a?(e.append(g),b.remove()):(f=t.$createListNode(a,"number"===a?Number(d[2]):void 0),f.append(g),b.replace(f));g.append(...c);(b=Math.floor(d[1].length/4))&&g.setIndent(b)},Y=
(a,b,c)=>{const d=[];var e=a.getChildren();let f=0;for(const h of e)if(t.$isListItemNode(h)){if(1===h.getChildrenSize()&&(e=h.getFirstChild(),t.$isListNode(e))){d.push(Y(e,b,c+1));continue}e=" ".repeat(4*c);var g=a.getListType();g="number"===g?`${a.getStart()+f}. `:"check"===g?`- [${h.getChecked()?"x":" "}] `:"- ";d.push(e+g+b(h));f++}return d.join("\n")},la={dependencies:[z.HeadingNode],export:(a,b)=>{if(!z.$isHeadingNode(a))return null;const c=Number(a.getTag().slice(1));return"#".repeat(c)+" "+
b(a)},regExp:/^(#{1,6})\s/,replace:W(a=>z.$createHeadingNode("h"+a[1].length)),type:"element"},ma={dependencies:[z.QuoteNode],export:(a,b)=>{if(!z.$isQuoteNode(a))return null;a=b(a).split("\n");b=[];for(const c of a)b.push("> "+c);return b.join("\n")},regExp:/^>\s/,replace:(a,b,c,d)=>{if(d&&(c=a.getPreviousSibling(),z.$isQuoteNode(c))){c.splice(c.getChildrenSize(),0,[l.$createLineBreakNode(),...b]);a.remove();return}c=z.$createQuoteNode();c.append(...b);a.replace(c)},type:"element"},na={dependencies:[A.CodeNode],
export:a=>{if(!A.$isCodeNode(a))return null;const b=a.getTextContent();return"```"+(a.getLanguage()||"")+(b?"\n"+b:"")+"\n```"},getNumberOfLines:(a,b)=>{const c=/^```(\w{1,10})?\s?$/;let d=b;const e=a.length;for(;++d<e&&!a[d].match(c););return d-b},regExp:/^```(\w{1,10})?\s?$/,replace:W(a=>A.$createCodeNode(a?a[1]:void 0)),type:"element"},oa={dependencies:[t.ListNode,t.ListItemNode],export:(a,b)=>t.$isListNode(a)?Y(a,b,0):null,regExp:/^(\s*)[-*+]\s/,replace:X("bullet"),type:"element"},pa={dependencies:[t.ListNode,
t.ListItemNode],export:(a,b)=>t.$isListNode(a)?Y(a,b,0):null,regExp:/^(\s*)(?:-\s)?\s?(\[(\s|x)?\])\s/i,replace:X("check"),type:"element"},qa={dependencies:[t.ListNode,t.ListItemNode],export:(a,b)=>t.$isListNode(a)?Y(a,b,0):null,regExp:/^(\s*)(\d{1,})\.\s/,replace:X("number"),type:"element"},ra={format:["code"],tag:"`",type:"text-format"},sa={format:["highlight"],tag:"==",type:"text-format"},ta={format:["bold","italic"],tag:"***",type:"text-format"},ua={format:["bold","italic"],intraword:!1,tag:"___",
type:"text-format"},wa={format:["bold"],tag:"**",type:"text-format"},xa={format:["bold"],intraword:!1,tag:"__",type:"text-format"},ya={format:["strikethrough"],tag:"~~",type:"text-format"},za={format:["italic"],tag:"*",type:"text-format"},Aa={format:["italic"],intraword:!1,tag:"_",type:"text-format"},Ba={dependencies:[G.LinkNode],export:(a,b,c)=>{if(!G.$isLinkNode(a))return null;b=(b=a.getTitle())?`[${a.getTextContent()}](${a.getURL()} "${b}")`:`[${a.getTextContent()}](${a.getURL()})`;const d=a.getFirstChild();
return 1===a.getChildrenSize()&&l.$isTextNode(d)?c(d,b):b},importRegExp:/(?:\[([^[]+)\])(?:\((?:([^()\s]+)(?:\s"((?:[^"]*\\")*[^"]*)"\s*)?)\))/,regExp:/(?:\[([^[]+)\])(?:\((?:([^()\s]+)(?:\s"((?:[^"]*\\")*[^"]*)"\s*)?)\))$/,replace:(a,b)=>{const [,c,d,e]=b;b=G.$createLinkNode(d,{title:e});const f=l.$createTextNode(c);f.setFormat(a.getFormat());b.append(f);a.replace(b)},trigger:")",type:"text-match"},Ca=[la,ma,na,oa,qa],Da=[ra,ta,ua,wa,xa,sa,za,Aa,ya],Ea=[Ba],Z=[...Ca,...Da,...Ea];
exports.$convertFromMarkdownString=function(a,b=Z,c){return ha(b)(a,c)};exports.$convertToMarkdownString=function(a=Z,b){return ba(a)(b)};exports.BOLD_ITALIC_STAR=ta;exports.BOLD_ITALIC_UNDERSCORE=ua;exports.BOLD_STAR=wa;exports.BOLD_UNDERSCORE=xa;exports.CHECK_LIST=pa;exports.CODE=na;exports.ELEMENT_TRANSFORMERS=Ca;exports.HEADING=la;exports.HIGHLIGHT=sa;exports.INLINE_CODE=ra;exports.ITALIC_STAR=za;exports.ITALIC_UNDERSCORE=Aa;exports.LINK=Ba;exports.ORDERED_LIST=qa;exports.QUOTE=ma;
exports.STRIKETHROUGH=ya;exports.TEXT_FORMAT_TRANSFORMERS=Da;exports.TEXT_MATCH_TRANSFORMERS=Ea;exports.TRANSFORMERS=Z;exports.UNORDERED_LIST=oa;exports.createBlockNode=W;
exports.registerMarkdownShortcuts=function(a,b=Z){let c=I(b),d=H(c.textFormat,({tag:f})=>f[f.length-1]),e=H(c.textMatch,({trigger:f})=>f);for(let f of b)if(b=f.type,"element"===b||"text-match"===b){b=f.dependencies;for(let g of b)if(!a.hasNode(g))throw Error(`MarkdownShortcuts: missing dependency ${g.getType()} for transformer. Ensure node dependency is included in editor initial config.`);}return a.registerUpdateListener(({tags:f,dirtyLeaves:g,editorState:h,prevEditorState:k})=>{if(!f.has("historic")&&
!a.isComposing()){var p=h.read(l.$getSelection);f=k.read(l.$getSelection);if(l.$isRangeSelection(f)&&l.$isRangeSelection(p)&&p.isCollapsed()){k=p.anchor.key;var B=p.anchor.offset,u=h._nodeMap.get(k);!l.$isTextNode(u)||!g.has(k)||1!==B&&B>f.anchor.offset+1||a.update(()=>{if(!u.hasFormat("code")){var q=u.getParent();if(null!==q&&!A.$isCodeNode(q)){var r=p.anchor.offset;b:{var m=c.element,n=q.getParent();if(l.$isRootOrShadowRoot(n)&&q.getFirstChild()===u&&(n=u.getTextContent()," "===n[r-1]))for(let {regExp:D,
replace:E}of m)if((m=n.match(D))&&m[0].length===r){n=u.getNextSiblings();let [F,va]=u.splitText(r);F.remove();n=va?[va,...n]:n;E(q,n,m,!1);q=!0;break b}q=!1}if(!q){b:{m=u.getTextContent();q=e[m[r-1]];if(null!=q){r<m.length&&(m=m.slice(0,r));for(w of q)if(q=m.match(w.regExp),null!==q){m=q.index||0;n=m+q[0].length;var x=void 0;0===m?[x]=u.splitText(n):[,x]=u.splitText(m,n);x.selectNext(0,0);w.replace(x,q);var w=!0;break b}}w=!1}if(!w)b:{n=u.getTextContent();--r;var v=n[r];if(w=d[v])for(let D of w){var {tag:C}=
D;w=C.length;let E=r-w+1;if(!(1<w&&!ka(n,E,C,0,w)||" "===n[E-1])&&(x=n[r+1],!1!==D.intraword||!x||J.test(x))){q=x=u;m=ja(n,E,C);for(var y=q;0>m&&(y=y.getPreviousSibling())&&!l.$isLineBreakNode(y);)l.$isTextNode(y)&&(m=y.getTextContent(),q=y,m=ja(m,m.length,C));if(!(0>m||q===x&&m+w===E||(C=q.getTextContent(),0<m&&C[m-1]===v||(y=C[m-1],!1===D.intraword&&y&&!J.test(y))))){n=x.getTextContent();n=n.slice(0,E)+n.slice(r+1);x.setTextContent(n);n=q===x?n:C;q.setTextContent(n.slice(0,m)+n.slice(m+w));n=l.$getSelection();
v=l.$createRangeSelection();l.$setSelection(v);r=r-w*(q===x?2:1)+1;v.anchor.set(q.__key,m,"text");v.focus.set(x.__key,r,"text");for(let F of D.format)v.hasFormat(F)||v.formatText(F);v.anchor.set(v.focus.key,v.focus.offset,v.focus.type);for(let F of D.format)v.hasFormat(F)&&v.toggleFormat(F);l.$isRangeSelection(n)&&(v.format=n.format);break b}}}}}}}})}}})}
