/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

'use strict';var k=require("lexical"),r=require("@lexical/list"),A=require("@lexical/rich-text"),aa=require("@lexical/utils"),F=require("@lexical/code"),G=require("@lexical/link");function H(a,b){let c={};for(let d of a)a=b(d),c[a]?c[a].push(d):c[a]=[d];return c}function I(a){a=H(a,b=>b.type);return{element:a.element||[],textFormat:a["text-format"]||[],textMatch:a["text-match"]||[]}}let J=/[!-/:-@[-`{-~\s]/;
function ba(a){let b=I(a),c=b.textFormat.filter(d=>1===d.format.length);return d=>{let e=[];d=(d||k.$getRoot()).getChildren();for(let f of d)d=ca(f,b.element,c,b.textMatch),null!=d&&e.push(d);return e.join("\n\n")}}function ca(a,b,c,d){for(let e of b){let f=e.export(a,g=>K(g,b,c,d));if(null!=f)return f}return k.$isElementNode(a)?K(a,b,c,d):k.$isDecoratorNode(a)?a.getTextContent():null}
function K(a,b,c,d){let e=[];a=a.getChildren();a:for(let g of a){if(k.$isElementNode(g))for(let h of b){var f=h.export(g,m=>K(m,b,c,d));if(null!=f){e.push(f);a.indexOf(g)!==a.length-1&&e.push("\n");continue a}}for(let h of d)if(f=h.export(g,m=>K(m,b,c,d),(m,n)=>L(m,n,c)),null!=f){e.push(f);continue a}k.$isLineBreakNode(g)?e.push("\n"):k.$isTextNode(g)?e.push(L(g,g.getTextContent(),c)):k.$isElementNode(g)?(e.push(K(g,b,c,d)),a.indexOf(g)!==a.length-1&&e.push("\n","\n")):k.$isDecoratorNode(g)&&e.push(g.getTextContent())}return e.join("")}
function L(a,b,c){let d=b.trim(),e=d,f=new Set;for(let h of c){c=h.format[0];let m=h.tag;if(M(a,c)&&!f.has(c)){f.add(c);var g=N(a,!0);M(g,c)||(e=m+e);g=N(a,!1);M(g,c)||(e+=m)}}return b.replace(d,()=>e)}
function N(a,b){let c=b?a.getPreviousSibling():a.getNextSibling();c||(a=a.getParentOrThrow(),a.isInline()&&(c=b?a.getPreviousSibling():a.getNextSibling()));for(;c;){if(k.$isElementNode(c)){if(!c.isInline())break;a=b?c.getLastDescendant():c.getFirstDescendant();if(k.$isTextNode(a))return a;c=b?c.getPreviousSibling():c.getNextSibling()}if(k.$isTextNode(c))return c;if(!k.$isElementNode(c))break}return null}function M(a,b){return k.$isTextNode(a)&&a.hasFormat(b)}
let O="undefined"!==typeof window&&"undefined"!==typeof window.document&&"undefined"!==typeof window.document.createElement,da=O&&"documentMode"in document?document.documentMode:null;O&&"InputEvent"in window&&!da?"getTargetRanges"in new window.InputEvent("input"):!1;
let P=O&&/Version\/[\d.]+.*Safari/.test(navigator.userAgent),Q=O&&/iPad|iPhone|iPod/.test(navigator.userAgent)&&!window.MSStream,ea=O&&/^(?=.*Chrome).*/i.test(navigator.userAgent),R=O&&/AppleWebKit\/[\d.]+/.test(navigator.userAgent)&&!ea,fa=/^\s{0,3}$/;
function S(a,b,c){let d=b.length;var e=c.textFormat;var f={};var g={},h=[];for(var m of e){({tag:e}=m);f[e]=m;var n=e.replace(/(\*|\^|\+)/g,"\\$1");h.push(n);g[e]=P||Q||R?new RegExp(`(${n})(?![${n}\\s])(.*?[^${n}\\s])${n}(?!${n})`):new RegExp(`(?<![\\\\${n}])(${n})((\\\\${n})?.*?[^${n}\\s](\\\\${n})?)((?<!\\\\)|(?<=\\\\\\\\))(${n})(?![\\\\${n}])`)}f={fullMatchRegExpByTag:g,openTagsRegExp:new RegExp((P||Q||R?"":"(?<![\\\\])")+"("+h.join("|")+")","g"),transformersByTag:f};for(g=0;g<d;){h=b[g];n=!1;
for(let l of c.element)if(m=h.match(l.regExp),l.getNumberOfLines&&(e=l.getNumberOfLines(b,g),!(g+e>b.length)&&m)){if(l.recursivelyParse)n=k.$createParagraphNode(),a.append(n),S(n,b.slice(g+1,g+e),c);else{n=k.$createTextNode(b.slice(g+1,g+e).join("\n"));var y=k.$createParagraphNode();y.append(n);a.append(y)}l.replace(a.getLastChild(),a.getLastChild().getChildren(),m,!0);g+=e;g<d&&l.closeRegExp&&b[g].match(l.closeRegExp)&&g++;n=!0;break}if(!n){var t=h,q=a,u=c.element;m=f;e=c.textMatch;n=t.trimEnd();
y=k.$createTextNode(n);h=k.$createParagraphNode();h.append(y);q.append(h);for(let {regExp:l,replace:p}of u)if(q=t.match(l)){t=t.slice(q[0].length);y.setTextContent(t);p(h,[y],q,!0);break}T(y,m,e);h.isAttached()&&0<n.length&&(m=h.getPreviousSibling(),k.$isParagraphNode(m)||A.$isQuoteNode(m)||r.$isListNode(m))&&(e=m,r.$isListNode(m)&&(m=m.getLastDescendant(),e=null==m?null:aa.$findMatchingParent(m,r.$isListItemNode)),null!=e&&0<e.getTextContentSize()&&(e.splice(e.getChildrenSize(),0,[k.$createLineBreakNode(),
...h.getChildren()]),h.remove()));g++}}}function U(a){a=a.getChildren();for(let b of a){a:{a=b;if(!k.$isParagraphNode(a)){a=!1;break a}let c=a.getFirstChild();a=null==c||1===a.getChildrenSize()&&k.$isTextNode(c)&&fa.test(c.getTextContent())}a?b.remove():k.$isElementNode(b)&&U(b)}}function ha(a){let b=I(a);return(c,d)=>{c=c.split("\n");d=d||k.$getRoot();d.clear();S(d,c,b);U(d);null!==k.$getSelection()&&d.selectEnd()}}
function T(a,b,c){var d=a.getTextContent();let e=ia(d,b);if(e){var f,g;if(e[0]===d)var h=a;else{d=e.index||0;let m=d+e[0].length;0===d?[h,f]=a.splitText(m):[g,h,f]=a.splitText(d,m)}h.setTextContent(e[2]);if(a=b.transformersByTag[e[1]])for(let m of a.format)h.hasFormat(m)||h.toggleFormat(m);h.hasFormat("code")||T(h,b,c);g&&T(g,b,c);f&&T(f,b,c)}else ja(a,c)}
function ja(a,b){a:for(;a;){for(let c of b){let d=a.getTextContent().match(c.importRegExp);if(!d)continue;let e=d.index||0,f=e+d[0].length,g,h;0===e?[g,a]=a.splitText(f):[,g,h]=a.splitText(e,f);h&&ja(h,b);c.replace(g,d);continue a}break}}
function ia(a,b){var c=a.match(b.openTagsRegExp);if(null==c)return null;for(let f of c){var d=f.replace(/^\s/,"");c=b.fullMatchRegExpByTag[d];if(null!=c&&(c=a.match(c),d=b.transformersByTag[d],null!=c&&null!=d)){if(!1!==d.intraword)return c;var {index:e=0}=c;d=a[e-1];e=a[e+c[0].length];if(!(d&&!J.test(d)||e&&!J.test(e)))return c}}return null}var ka;
function V(a){let b=new URLSearchParams;b.append("code",a);for(let c=1;c<arguments.length;c++)b.append("v",arguments[c]);throw Error(`Minified Lexical error #${a}; visit https://lexical.dev/docs/error?${b} for the full message or `+"use the non-minified dev environment for full errors and additional helpful warnings.");}ka=V&&V.__esModule&&Object.prototype.hasOwnProperty.call(V,"default")?V["default"]:V;
function la(a,b,c){let d=c.length;for(;b>=d;b--){let e=b-d;if(ma(a,e,c,0,d)&&" "!==a[e+d])return e}return-1}function ma(a,b,c,d,e){for(let f=0;f<e;f++)if(a[b+f]!==c[d+f])return!1;return!0}
let W=a=>(b,c,d)=>{d=a(d);d.append(...c);b.replace(d)},X=a=>(b,c,d)=>{var e=b.getPreviousSibling(),f=b.getNextSibling();const g=r.$createListItemNode("check"===a?"x"===d[3]:void 0);r.$isListNode(f)&&f.getListType()===a?(e=f.getFirstChild(),null!==e?e.insertBefore(g):f.append(g),b.remove()):r.$isListNode(e)&&e.getListType()===a?(e.append(g),b.remove()):(f=r.$createListNode(a,"number"===a?Number(d[2]):void 0),f.append(g),b.replace(f));g.append(...c);(b=Math.floor(d[1].length/4))&&g.setIndent(b)},Y=
(a,b,c)=>{const d=[];var e=a.getChildren();let f=0;for(const h of e)if(r.$isListItemNode(h)){if(1===h.getChildrenSize()&&(e=h.getFirstChild(),r.$isListNode(e))){d.push(Y(e,b,c+1));continue}e=" ".repeat(4*c);var g=a.getListType();g="number"===g?`${a.getStart()+f}. `:"check"===g?`- [${h.getChecked()?"x":" "}] `:"- ";d.push(e+g+b(h));f++}return d.join("\n")},na={dependencies:[A.HeadingNode],export:(a,b)=>{if(!A.$isHeadingNode(a))return null;const c=Number(a.getTag().slice(1));return"#".repeat(c)+" "+
b(a)},regExp:/^(#{1,6})\s/,replace:W(a=>A.$createHeadingNode("h"+a[1].length)),type:"element"},oa={dependencies:[A.QuoteNode],export:(a,b)=>{if(!A.$isQuoteNode(a))return null;a=b(a).split("\n");b=[];for(const c of a)b.push("> "+c);return b.join("\n")},regExp:/^>\s/,replace:(a,b,c,d)=>{if(d&&(c=a.getPreviousSibling(),A.$isQuoteNode(c))){c.splice(c.getChildrenSize(),0,[k.$createLineBreakNode(),...b]);a.remove();return}c=A.$createQuoteNode();c.append(...b);a.replace(c)},type:"element"},pa={closeRegExp:/^```$/,
dependencies:[F.CodeNode],export:a=>{if(!F.$isCodeNode(a))return null;const b=a.getTextContent();return"```"+(a.getLanguage()||"")+(b?"\n"+b:"")+"\n```"},getNumberOfLines:(a,b)=>{const c=/^```(\w{1,10})?\s?$/;let d=b;const e=a.length;for(;++d<e&&!a[d].match(c););return d-b},regExp:/^```(\w{1,10})?\s?$/,replace:W(a=>F.$createCodeNode(a?a[1]:void 0)),type:"element"},qa={dependencies:[r.ListNode,r.ListItemNode],export:(a,b)=>r.$isListNode(a)?Y(a,b,0):null,regExp:/^(\s*)[-*+]\s/,replace:X("bullet"),type:"element"},
ra={dependencies:[r.ListNode,r.ListItemNode],export:(a,b)=>r.$isListNode(a)?Y(a,b,0):null,regExp:/^(\s*)(?:-\s)?\s?(\[(\s|x)?\])\s/i,replace:X("check"),type:"element"},sa={dependencies:[r.ListNode,r.ListItemNode],export:(a,b)=>r.$isListNode(a)?Y(a,b,0):null,regExp:/^(\s*)(\d{1,})\.\s/,replace:X("number"),type:"element"},ta={format:["code"],tag:"`",type:"text-format"},ua={format:["highlight"],tag:"==",type:"text-format"},va={format:["bold","italic"],tag:"***",type:"text-format"},wa={format:["bold",
"italic"],intraword:!1,tag:"___",type:"text-format"},ya={format:["bold"],tag:"**",type:"text-format"},za={format:["bold"],intraword:!1,tag:"__",type:"text-format"},Aa={format:["strikethrough"],tag:"~~",type:"text-format"},Ba={format:["italic"],tag:"*",type:"text-format"},Ca={format:["italic"],intraword:!1,tag:"_",type:"text-format"},Da={dependencies:[G.LinkNode],export:(a,b,c)=>{if(!G.$isLinkNode(a))return null;b=(b=a.getTitle())?`[${a.getTextContent()}](${a.getURL()} "${b}")`:`[${a.getTextContent()}](${a.getURL()})`;
const d=a.getFirstChild();return 1===a.getChildrenSize()&&k.$isTextNode(d)?c(d,b):b},importRegExp:/(?:\[([^[]+)\])(?:\((?:([^()\s]+)(?:\s"((?:[^"]*\\")*[^"]*)"\s*)?)\))/,regExp:/(?:\[([^[]+)\])(?:\((?:([^()\s]+)(?:\s"((?:[^"]*\\")*[^"]*)"\s*)?)\))$/,replace:(a,b)=>{const [,c,d,e]=b;b=G.$createLinkNode(d,{title:e});const f=k.$createTextNode(c);f.setFormat(a.getFormat());b.append(f);a.replace(b)},trigger:")",type:"text-match"},Ea=[na,oa,pa,qa,sa],Fa=[ta,va,wa,ya,za,ua,Ba,Ca,Aa],Ga=[Da],Z=[...Ea,...Fa,
...Ga];exports.$convertFromMarkdownString=function(a,b=Z,c){return ha(b)(a,c)};exports.$convertToMarkdownString=function(a=Z,b){return ba(a)(b)};exports.BOLD_ITALIC_STAR=va;exports.BOLD_ITALIC_UNDERSCORE=wa;exports.BOLD_STAR=ya;exports.BOLD_UNDERSCORE=za;exports.CHECK_LIST=ra;exports.CODE=pa;exports.ELEMENT_TRANSFORMERS=Ea;exports.HEADING=na;exports.HIGHLIGHT=ua;exports.INLINE_CODE=ta;exports.ITALIC_STAR=Ba;exports.ITALIC_UNDERSCORE=Ca;exports.LINK=Da;exports.ORDERED_LIST=sa;exports.QUOTE=oa;
exports.STRIKETHROUGH=Aa;exports.TEXT_FORMAT_TRANSFORMERS=Fa;exports.TEXT_MATCH_TRANSFORMERS=Ga;exports.TRANSFORMERS=Z;exports.UNORDERED_LIST=qa;exports.createBlockNode=W;
exports.registerMarkdownShortcuts=function(a,b=Z){let c=I(b),d=H(c.textFormat,({tag:f})=>f[f.length-1]),e=H(c.textMatch,({trigger:f})=>f);for(let f of b)if(b=f.type,"element"===b||"text-match"===b){b=f.dependencies;for(let g of b)a.hasNode(g)||ka(173,g.getType())}return a.registerUpdateListener(({tags:f,dirtyLeaves:g,editorState:h,prevEditorState:m})=>{if(!f.has("collaboration")&&!f.has("historic")&&!a.isComposing()){var n=h.read(k.$getSelection);f=m.read(k.$getSelection);if(k.$isRangeSelection(f)&&
k.$isRangeSelection(n)&&n.isCollapsed()){m=n.anchor.key;var y=n.anchor.offset,t=h._nodeMap.get(m);!k.$isTextNode(t)||!g.has(m)||1!==y&&y>f.anchor.offset+1||a.update(()=>{if(!t.hasFormat("code")){var q=t.getParent();if(null!==q&&!F.$isCodeNode(q)){var u=n.anchor.offset;b:{var l=c.element,p=q.getParent();if(k.$isRootOrShadowRoot(p)&&q.getFirstChild()===t&&(p=t.getTextContent()," "===p[u-1]))for(let {regExp:C,replace:D}of l)if((l=p.match(C))&&l[0].length===u){p=t.getNextSiblings();let [E,xa]=t.splitText(u);
E.remove();p=xa?[xa,...p]:p;D(q,p,l,!1);q=!0;break b}q=!1}if(!q){b:{l=t.getTextContent();q=e[l[u-1]];if(null!=q){u<l.length&&(l=l.slice(0,u));for(w of q)if(q=l.match(w.regExp),null!==q){l=q.index||0;p=l+q[0].length;var x=void 0;0===l?[x]=t.splitText(p):[,x]=t.splitText(l,p);x.selectNext(0,0);w.replace(x,q);var w=!0;break b}}w=!1}if(!w)b:{p=t.getTextContent();--u;var v=p[u];if(w=d[v])for(let C of w){var {tag:B}=C;w=B.length;let D=u-w+1;if(!(1<w&&!ma(p,D,B,0,w)||" "===p[D-1])&&(x=p[u+1],!1!==C.intraword||
!x||J.test(x))){q=x=t;l=la(p,D,B);for(var z=q;0>l&&(z=z.getPreviousSibling())&&!k.$isLineBreakNode(z);)k.$isTextNode(z)&&(l=z.getTextContent(),q=z,l=la(l,l.length,B));if(!(0>l||q===x&&l+w===D||(B=q.getTextContent(),0<l&&B[l-1]===v||(z=B[l-1],!1===C.intraword&&z&&!J.test(z))))){p=x.getTextContent();p=p.slice(0,D)+p.slice(u+1);x.setTextContent(p);p=q===x?p:B;q.setTextContent(p.slice(0,l)+p.slice(l+w));p=k.$getSelection();v=k.$createRangeSelection();k.$setSelection(v);u=u-w*(q===x?2:1)+1;v.anchor.set(q.__key,
l,"text");v.focus.set(x.__key,u,"text");for(let E of C.format)v.hasFormat(E)||v.formatText(E);v.anchor.set(v.focus.key,v.focus.offset,v.focus.type);for(let E of C.format)v.hasFormat(E)&&v.toggleFormat(E);k.$isRangeSelection(p)&&(v.format=p.format);break b}}}}}}}})}}})}
