/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */
'use strict';var l=require("lexical"),r=require("@lexical/list"),A=require("@lexical/rich-text"),aa=require("@lexical/utils"),B=require("@lexical/code"),G=require("@lexical/link");function H(a,b){let c={};for(let d of a)a=b(d),c[a]?c[a].push(d):c[a]=[d];return c}function I(a){a=H(a,b=>b.type);return{element:a.element||[],textFormat:a["text-format"]||[],textMatch:a["text-match"]||[]}}let J=/[!-/:-@[-`{-~\s]/;
function ba(a){let b=I(a),c=b.textFormat.filter(d=>1===d.format.length);return d=>{let e=[];d=(d||l.$getRoot()).getChildren();for(let g of d)d=ca(g,b.element,c,b.textMatch),null!=d&&e.push(d);return e.join("\n\n")}}function ca(a,b,c,d){for(let e of b){let g=e.export(a,f=>K(f,b,c,d));if(null!=g)return g}return l.$isElementNode(a)?K(a,b,c,d):l.$isDecoratorNode(a)?a.getTextContent():null}
function K(a,b,c,d){let e=[];a=a.getChildren();a:for(let f of a){if(l.$isElementNode(f))for(let h of b){var g=h.export(f,k=>K(k,b,c,d));if(null!=g){e.push(g);a.indexOf(f)!==a.length-1&&e.push("\n");continue a}}for(let h of d)if(g=h.export(f,k=>K(k,b,c,d),(k,n)=>L(k,n,c)),null!=g){e.push(g);continue a}l.$isLineBreakNode(f)?e.push("\n"):l.$isTextNode(f)?e.push(L(f,f.getTextContent(),c)):l.$isElementNode(f)?(e.push(K(f,b,c,d)),a.indexOf(f)!==a.length-1&&e.push("\n","\n")):l.$isDecoratorNode(f)&&e.push(f.getTextContent())}return e.join("")}
function L(a,b,c){let d=b.trim(),e=d,g=new Set;for(let h of c){c=h.format[0];let k=h.tag;if(M(a,c)&&!g.has(c)){g.add(c);var f=N(a,!0);M(f,c)||(e=k+e);f=N(a,!1);M(f,c)||(e+=k)}}return b.replace(d,e)}
function N(a,b){let c=b?a.getPreviousSibling():a.getNextSibling();c||(a=a.getParentOrThrow(),a.isInline()&&(c=b?a.getPreviousSibling():a.getNextSibling()));for(;c;){if(l.$isElementNode(c)){if(!c.isInline())break;a=b?c.getLastDescendant():c.getFirstDescendant();if(l.$isTextNode(a))return a;c=b?c.getPreviousSibling():c.getNextSibling()}if(l.$isTextNode(c))return c;if(!l.$isElementNode(c))break}return null}function M(a,b){return l.$isTextNode(a)&&a.hasFormat(b)}
let O="undefined"!==typeof window&&"undefined"!==typeof window.document&&"undefined"!==typeof window.document.createElement,da=O&&"documentMode"in document?document.documentMode:null;O&&/Mac|iPod|iPhone|iPad/.test(navigator.platform);O&&/^(?!.*Seamonkey)(?=.*Firefox).*/i.test(navigator.userAgent);O&&"InputEvent"in window&&!da?"getTargetRanges"in new window.InputEvent("input"):!1;
let P=O&&/Version\/[\d.]+.*Safari/.test(navigator.userAgent),Q=O&&/iPad|iPhone|iPod/.test(navigator.userAgent)&&!window.MSStream,ea=O&&/^(?=.*Chrome).*/i.test(navigator.userAgent),R=O&&/AppleWebKit\/[\d.]+/.test(navigator.userAgent)&&!ea,fa=/^\s{0,3}$/;
function S(a,b,c){let d=b.length;var e=c.textFormat;var g={};var f={},h=[];for(var k of e){({tag:e}=k);g[e]=k;var n=e.replace(/(\*|\^|\+)/g,"\\$1");h.push(n);f[e]=P||Q||R?new RegExp(`(${n})(?![${n}\\s])(.*?[^${n}\\s])${n}(?!${n})`):new RegExp(`(?<![\\\\${n}])(${n})((\\\\${n})?.*?[^${n}\\s](\\\\${n})?)((?<!\\\\)|(?<=\\\\\\\\))(${n})(?![\\\\${n}])`)}g={fullMatchRegExpByTag:f,openTagsRegExp:new RegExp((P||Q||R?"":"(?<![\\\\])")+"("+h.join("|")+")","g"),transformersByTag:g};for(f=0;f<d;){h=b[f];n=!1;
for(let m of c.element)if(k=h.match(m.regExp),m.getNumberOfLines&&(e=m.getNumberOfLines(b,f),!(f+e>b.length)&&k)){if(m.recursivelyParse)n=l.$createParagraphNode(),a.append(n),S(n,b.slice(f+1,f+e),c);else{n=l.$createTextNode(b.slice(f+1,f+e).join("\n"));var y=l.$createParagraphNode();y.append(n);a.append(y)}m.replace(a.getLastChild(),a.getLastChild().getChildren(),k,!0);f+=e;f<d&&m.closeRegExp&&b[f].match(m.closeRegExp)&&f++;n=!0;break}if(!n){var t=h,q=a,u=c.element;k=g;e=c.textMatch;n=t.trimEnd();
y=l.$createTextNode(n);h=l.$createParagraphNode();h.append(y);q.append(h);for(let {regExp:m,replace:p}of u)if(q=t.match(m)){t=t.slice(q[0].length);y.setTextContent(t);p(h,[y],q,!0);break}T(y,k,e);h.isAttached()&&0<n.length&&(k=h.getPreviousSibling(),l.$isParagraphNode(k)||A.$isQuoteNode(k)||r.$isListNode(k))&&(e=k,r.$isListNode(k)&&(k=k.getLastDescendant(),e=null==k?null:aa.$findMatchingParent(k,r.$isListItemNode)),null!=e&&0<e.getTextContentSize()&&(e.splice(e.getChildrenSize(),0,[l.$createLineBreakNode(),
...h.getChildren()]),h.remove()));f++}}}function U(a){a=a.getChildren();for(let b of a){a:{a=b;if(!l.$isParagraphNode(a)){a=!1;break a}let c=a.getFirstChild();a=null==c||1===a.getChildrenSize()&&l.$isTextNode(c)&&fa.test(c.getTextContent())}a?b.remove():l.$isElementNode(b)&&U(b)}}function ha(a){let b=I(a);return(c,d)=>{c=c.split("\n");d=d||l.$getRoot();d.clear();S(d,c,b);U(d);null!==l.$getSelection()&&d.selectEnd()}}
function T(a,b,c){var d=a.getTextContent();let e=ia(d,b);if(e){var g,f;if(e[0]===d)var h=a;else{d=e.index||0;let k=d+e[0].length;0===d?[h,g]=a.splitText(k):[f,h,g]=a.splitText(d,k)}h.setTextContent(e[2]);if(a=b.transformersByTag[e[1]])for(let k of a.format)h.hasFormat(k)||h.toggleFormat(k);h.hasFormat("code")||T(h,b,c);f&&T(f,b,c);g&&T(g,b,c)}else V(a,c)}
function V(a,b){a:for(;a;){for(let c of b){let d=a.getTextContent().match(c.importRegExp);if(!d)continue;let e=d.index||0,g=e+d[0].length,f,h,k;0===e?[f,a]=a.splitText(g):[h,f,k]=a.splitText(e,g);h&&V(h,b);k&&(a=k);c.replace(f,d);continue a}break}}
function ia(a,b){var c=a.match(b.openTagsRegExp);if(null==c)return null;for(let g of c){var d=g.replace(/^\s/,"");c=b.fullMatchRegExpByTag[d];if(null!=c&&(c=a.match(c),d=b.transformersByTag[d],null!=c&&null!=d)){if(!1!==d.intraword)return c;var {index:e=0}=c;d=a[e-1];e=a[e+c[0].length];if(!(d&&!J.test(d)||e&&!J.test(e)))return c}}return null}function ja(a,b,c){let d=c.length;for(;b>=d;b--){let e=b-d;if(ka(a,e,c,0,d)&&" "!==a[e+d])return e}return-1}
function ka(a,b,c,d,e){for(let g=0;g<e;g++)if(a[b+g]!==c[d+g])return!1;return!0}
let W=a=>(b,c,d)=>{d=a(d);d.append(...c);b.replace(d)},X=a=>(b,c,d)=>{var e=b.getPreviousSibling(),g=b.getNextSibling();const f=r.$createListItemNode("check"===a?"x"===d[3]:void 0);r.$isListNode(g)&&g.getListType()===a?(e=g.getFirstChild(),null!==e?e.insertBefore(f):g.append(f),b.remove()):r.$isListNode(e)&&e.getListType()===a?(e.append(f),b.remove()):(g=r.$createListNode(a,"number"===a?Number(d[2]):void 0),g.append(f),b.replace(g));f.append(...c);(b=Math.floor(d[1].length/4))&&f.setIndent(b)},Y=
(a,b,c)=>{const d=[];var e=a.getChildren();let g=0;for(const h of e)if(r.$isListItemNode(h)){if(1===h.getChildrenSize()&&(e=h.getFirstChild(),r.$isListNode(e))){d.push(Y(e,b,c+1));continue}e=" ".repeat(4*c);var f=a.getListType();f="number"===f?`${a.getStart()+g}. `:"check"===f?`- [${h.getChecked()?"x":" "}] `:"- ";d.push(e+f+b(h));g++}return d.join("\n")},la={dependencies:[A.HeadingNode],export:(a,b)=>{if(!A.$isHeadingNode(a))return null;const c=Number(a.getTag().slice(1));return"#".repeat(c)+" "+
b(a)},regExp:/^(#{1,6})\s/,replace:W(a=>A.$createHeadingNode("h"+a[1].length)),type:"element"},ma={dependencies:[A.QuoteNode],export:(a,b)=>{if(!A.$isQuoteNode(a))return null;a=b(a).split("\n");b=[];for(const c of a)b.push("> "+c);return b.join("\n")},regExp:/^>\s/,replace:(a,b,c,d)=>{if(d&&(c=a.getPreviousSibling(),A.$isQuoteNode(c))){c.splice(c.getChildrenSize(),0,[l.$createLineBreakNode(),...b]);a.remove();return}c=A.$createQuoteNode();c.append(...b);a.replace(c)},type:"element"},na={closeRegExp:/^```$/,
dependencies:[B.CodeNode],export:a=>{if(!B.$isCodeNode(a))return null;const b=a.getTextContent();return"```"+(a.getLanguage()||"")+(b?"\n"+b:"")+"\n```"},getNumberOfLines:(a,b)=>{const c=/^```(\w{1,10})?\s?$/;let d=b;const e=a.length;for(;++d<e&&!a[d].match(c););return d-b},regExp:/^```(\w{1,10})?\s?$/,replace:W(a=>B.$createCodeNode(a?a[1]:void 0)),type:"element"},oa={dependencies:[r.ListNode,r.ListItemNode],export:(a,b)=>r.$isListNode(a)?Y(a,b,0):null,regExp:/^(\s*)[-*+]\s/,replace:X("bullet"),type:"element"},
pa={dependencies:[r.ListNode,r.ListItemNode],export:(a,b)=>r.$isListNode(a)?Y(a,b,0):null,regExp:/^(\s*)(?:-\s)?\s?(\[(\s|x)?\])\s/i,replace:X("check"),type:"element"},qa={dependencies:[r.ListNode,r.ListItemNode],export:(a,b)=>r.$isListNode(a)?Y(a,b,0):null,regExp:/^(\s*)(\d{1,})\.\s/,replace:X("number"),type:"element"},ra={format:["code"],tag:"`",type:"text-format"},sa={format:["highlight"],tag:"==",type:"text-format"},ta={format:["bold","italic"],tag:"***",type:"text-format"},ua={format:["bold",
"italic"],intraword:!1,tag:"___",type:"text-format"},wa={format:["bold"],tag:"**",type:"text-format"},xa={format:["bold"],intraword:!1,tag:"__",type:"text-format"},ya={format:["strikethrough"],tag:"~~",type:"text-format"},za={format:["italic"],tag:"*",type:"text-format"},Aa={format:["italic"],intraword:!1,tag:"_",type:"text-format"},Ba={dependencies:[G.LinkNode],export:(a,b,c)=>{if(!G.$isLinkNode(a))return null;b=(b=a.getTitle())?`[${a.getTextContent()}](${a.getURL()} "${b}")`:`[${a.getTextContent()}](${a.getURL()})`;
const d=a.getFirstChild();return 1===a.getChildrenSize()&&l.$isTextNode(d)?c(d,b):b},importRegExp:/(?:\[([^[]+)\])(?:\((?:([^()\s]+)(?:\s"((?:[^"]*\\")*[^"]*)"\s*)?)\))/,regExp:/(?:\[([^[]+)\])(?:\((?:([^()\s]+)(?:\s"((?:[^"]*\\")*[^"]*)"\s*)?)\))$/,replace:(a,b)=>{const [,c,d,e]=b;b=G.$createLinkNode(d,{title:e});const g=l.$createTextNode(c);g.setFormat(a.getFormat());b.append(g);a.replace(b)},trigger:")",type:"text-match"},Ca=[la,ma,na,oa,qa],Da=[ra,ta,ua,wa,xa,sa,za,Aa,ya],Ea=[Ba],Z=[...Ca,...Da,
...Ea];exports.$convertFromMarkdownString=function(a,b=Z,c){return ha(b)(a,c)};exports.$convertToMarkdownString=function(a=Z,b){return ba(a)(b)};exports.BOLD_ITALIC_STAR=ta;exports.BOLD_ITALIC_UNDERSCORE=ua;exports.BOLD_STAR=wa;exports.BOLD_UNDERSCORE=xa;exports.CHECK_LIST=pa;exports.CODE=na;exports.ELEMENT_TRANSFORMERS=Ca;exports.HEADING=la;exports.HIGHLIGHT=sa;exports.INLINE_CODE=ra;exports.ITALIC_STAR=za;exports.ITALIC_UNDERSCORE=Aa;exports.LINK=Ba;exports.ORDERED_LIST=qa;exports.QUOTE=ma;
exports.STRIKETHROUGH=ya;exports.TEXT_FORMAT_TRANSFORMERS=Da;exports.TEXT_MATCH_TRANSFORMERS=Ea;exports.TRANSFORMERS=Z;exports.UNORDERED_LIST=oa;exports.createBlockNode=W;
exports.registerMarkdownShortcuts=function(a,b=Z){let c=I(b),d=H(c.textFormat,({tag:g})=>g[g.length-1]),e=H(c.textMatch,({trigger:g})=>g);for(let g of b)if(b=g.type,"element"===b||"text-match"===b){b=g.dependencies;for(let f of b)if(!a.hasNode(f))throw Error(`MarkdownShortcuts: missing dependency ${f.getType()} for transformer. Ensure node dependency is included in editor initial config.`);}return a.registerUpdateListener(({tags:g,dirtyLeaves:f,editorState:h,prevEditorState:k})=>{if(!g.has("historic")&&
!a.isComposing()){var n=h.read(l.$getSelection);g=k.read(l.$getSelection);if(l.$isRangeSelection(g)&&l.$isRangeSelection(n)&&n.isCollapsed()){k=n.anchor.key;var y=n.anchor.offset,t=h._nodeMap.get(k);!l.$isTextNode(t)||!f.has(k)||1!==y&&y>g.anchor.offset+1||a.update(()=>{if(!t.hasFormat("code")){var q=t.getParent();if(null!==q&&!B.$isCodeNode(q)){var u=n.anchor.offset;b:{var m=c.element,p=q.getParent();if(l.$isRootOrShadowRoot(p)&&q.getFirstChild()===t&&(p=t.getTextContent()," "===p[u-1]))for(let {regExp:D,
replace:E}of m)if((m=p.match(D))&&m[0].length===u){p=t.getNextSiblings();let [F,va]=t.splitText(u);F.remove();p=va?[va,...p]:p;E(q,p,m,!1);q=!0;break b}q=!1}if(!q){b:{m=t.getTextContent();q=e[m[u-1]];if(null!=q){u<m.length&&(m=m.slice(0,u));for(w of q)if(q=m.match(w.regExp),null!==q){m=q.index||0;p=m+q[0].length;var x=void 0;0===m?[x]=t.splitText(p):[,x]=t.splitText(m,p);x.selectNext(0,0);w.replace(x,q);var w=!0;break b}}w=!1}if(!w)b:{p=t.getTextContent();--u;var v=p[u];if(w=d[v])for(let D of w){var {tag:C}=
D;w=C.length;let E=u-w+1;if(!(1<w&&!ka(p,E,C,0,w)||" "===p[E-1])&&(x=p[u+1],!1!==D.intraword||!x||J.test(x))){q=x=t;m=ja(p,E,C);for(var z=q;0>m&&(z=z.getPreviousSibling())&&!l.$isLineBreakNode(z);)l.$isTextNode(z)&&(m=z.getTextContent(),q=z,m=ja(m,m.length,C));if(!(0>m||q===x&&m+w===E||(C=q.getTextContent(),0<m&&C[m-1]===v||(z=C[m-1],!1===D.intraword&&z&&!J.test(z))))){p=x.getTextContent();p=p.slice(0,E)+p.slice(u+1);x.setTextContent(p);p=q===x?p:C;q.setTextContent(p.slice(0,m)+p.slice(m+w));p=l.$getSelection();
v=l.$createRangeSelection();l.$setSelection(v);u=u-w*(q===x?2:1)+1;v.anchor.set(q.__key,m,"text");v.focus.set(x.__key,u,"text");for(let F of D.format)v.hasFormat(F)||v.formatText(F);v.anchor.set(v.focus.key,v.focus.offset,v.focus.type);for(let F of D.format)v.hasFormat(F)&&v.toggleFormat(F);l.$isRangeSelection(p)&&(v.format=p.format);break b}}}}}}}})}}})}
