/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

'use strict';var d=require("@lexical/utils"),x=require("lexical");
function y(b,a,n,h,f){if(null===b||0===n.size&&0===h.size&&!f)return 0;var c=a._selection,e=b._selection;if(f)return 1;if(!(x.$isRangeSelection(c)&&x.$isRangeSelection(e)&&e.isCollapsed()&&c.isCollapsed()))return 0;f=a._nodeMap;let g=[];for(let p of n)n=f.get(p),void 0!==n&&g.push(n);for(let [p,m]of h)m&&(h=f.get(p),void 0===h||x.$isRootNode(h)||g.push(h));if(0===g.length)return 0;if(1<g.length)return h=a._nodeMap,a=h.get(c.anchor.key),e=h.get(e.anchor.key),a&&e&&!b._nodeMap.has(a.__key)&&x.$isTextNode(a)&&
1===a.__text.length&&1===c.anchor.offset?2:0;a=g[0];b=b._nodeMap.get(a.__key);if(!x.$isTextNode(b)||!x.$isTextNode(a)||b.__mode!==a.__mode)return 0;b=b.__text;a=a.__text;if(b===a)return 0;c=c.anchor;e=e.anchor;if(c.key!==e.key||"text"!==c.type)return 0;c=c.offset;e=e.offset;b=a.length-b.length;return 1===b&&e===c-1?2:-1===b&&e===c+1?3:-1===b&&e===c?4:0}
function z(b,a){let n=Date.now(),h=0;return(f,c,e,g,p,m)=>{let q=Date.now();if(m.has("historic"))return h=0,n=q,2;let r=y(f,c,g,p,b.isComposing()),v=(()=>{var l=null===e||e.editor===b,k=m.has("history-push");if(!k&&l&&m.has("history-merge"))return 0;if(null===f)return 1;var t=c._selection;if(!(0<g.size||0<p.size))return null!==t?0:2;if(!1===k&&0!==r&&r===h&&q<n+a&&l)return 0;if(1===g.size){{k=Array.from(g)[0];l=f._nodeMap.get(k);k=c._nodeMap.get(k);t=f._selection;let u=c._selection,w=!1;x.$isRangeSelection(t)&&
x.$isRangeSelection(u)&&(w="element"===t.anchor.type&&"element"===t.focus.type&&"text"===u.anchor.type&&"text"===u.focus.type);l=!w&&x.$isTextNode(l)&&x.$isTextNode(k)?l.__type===k.__type&&l.__text===k.__text&&l.__mode===k.__mode&&l.__detail===k.__detail&&l.__style===k.__style&&l.__format===k.__format&&l.__parent===k.__parent:!1}if(l)return 0}return 1})();n=q;h=r;return v}}exports.createEmptyHistoryState=function(){return{current:null,redoStack:[],undoStack:[]}};
exports.registerHistory=function(b,a,n){let h=z(b,n);return d.mergeRegister(b.registerCommand(x.UNDO_COMMAND,()=>{let f=a.redoStack,c=a.undoStack;if(0!==c.length){let e=a.current,g=c.pop();null!==e&&(f.push(e),b.dispatchCommand(x.CAN_REDO_COMMAND,!0));0===c.length&&b.dispatchCommand(x.CAN_UNDO_COMMAND,!1);a.current=g||null;g&&g.editor.setEditorState(g.editorState,{tag:"historic"})}return!0},x.COMMAND_PRIORITY_EDITOR),b.registerCommand(x.REDO_COMMAND,()=>{let f=a.redoStack;var c=a.undoStack;if(0!==
f.length){let e=a.current;null!==e&&(c.push(e),b.dispatchCommand(x.CAN_UNDO_COMMAND,!0));c=f.pop();0===f.length&&b.dispatchCommand(x.CAN_REDO_COMMAND,!1);a.current=c||null;c&&c.editor.setEditorState(c.editorState,{tag:"historic"})}return!0},x.COMMAND_PRIORITY_EDITOR),b.registerCommand(x.CLEAR_EDITOR_COMMAND,()=>{a.undoStack=[];a.redoStack=[];a.current=null;return!1},x.COMMAND_PRIORITY_EDITOR),b.registerCommand(x.CLEAR_HISTORY_COMMAND,()=>{a.undoStack=[];a.redoStack=[];a.current=null;b.dispatchCommand(x.CAN_REDO_COMMAND,
!1);b.dispatchCommand(x.CAN_UNDO_COMMAND,!1);return!0},x.COMMAND_PRIORITY_EDITOR),b.registerUpdateListener(({editorState:f,prevEditorState:c,dirtyLeaves:e,dirtyElements:g,tags:p})=>{const m=a.current,q=a.redoStack,r=a.undoStack,v=null===m?null:m.editorState;if(null===m||f!==v){c=h(c,f,m,e,g,p);if(1===c)0!==q.length&&(a.redoStack=[],b.dispatchCommand(x.CAN_REDO_COMMAND,!1)),null!==m&&(r.push({...m}),b.dispatchCommand(x.CAN_UNDO_COMMAND,!0));else if(2===c)return;a.current={editor:b,editorState:f}}}))}
